server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: api-gateway
  config:
    import: "optional:config-server:http://localhost:8077/"
  cloud:
    gateway:
      routes:
        - id: loan-application-service
          uri: lb://loan-application-service
          predicates:
            - Path=/api/loans/**
        - id: loan-approval-service
          uri: lb://loan-approval-service
          predicates:
            - Path=/api/loan-disbursement/**

#  routes:
#    - id: selfService-route-1
#      uri: lb://SELFSERVICE
#      predicates:
#        - Path=/api/v1/users/**
#      filters:
#        - AuthenticationFilter
#    - id: selfService-route-2
#      uri: lb://SELFSERVICE  # Load balance to the "selfservice" service registered with Eureka
#      predicates:
#        - Path=/api/v1/customers/**
#      filters:
#        - AuthenticationFilter
#  cloud:
#    gateway:
#      routes:
#        - id: loan-application-service
#          uri: lb://LOAN-APPLICATION-SERVICE
#          predicates:
#            - Path=/api/loans/**
#          filters:
#            - RewritePath=/api/loans/(?<segment>.*), /${segment}
#
#        - id: loan-approval-service
#          uri: lb://LOAN-APPROVAL-SERVICE
#          predicates:
#            - Path=/api/loan-disbursement/**
#          filters:
#            - RewritePath=/api/loan-disbursement/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
