spring:
  application:
    name: loan-application-service
  datasource:
    url: jdbc:mysql://localhost:3306/loan_application_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  security:
#    user:
#      name: admin
#      password: admin_password
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: loan-group
#  cloud:
#    config:
#      uri: http://localhost:8888
#    loadbalancer:
#      ribbon:
#        enabled: false

server:
  port: 8078

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

#resilience4j:
#  circuitbreaker:
#    instances:
#      loanService:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

#feign:
#  circuitbreaker:
#    enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
